/*
	SELECT 
	 [DBO].[FN_FORMATA_DOCUMENTO]('01683328094')
	,[DBO].[FN_FORMATA_DOCUMENTO]('89723977000140')
*/

CREATE OR ALTER FUNCTION [DBO].[FN_FORMATA_DOCUMENTO](
    @NR_DOCUMENTO VARCHAR(MAX)
)
RETURNS VARCHAR(MAX)
WITH SCHEMABINDING
AS BEGIN

    SET @NR_DOCUMENTO = REPLACE(@NR_DOCUMENTO,'.','')
    SET @NR_DOCUMENTO = REPLACE(@NR_DOCUMENTO,'/','')
    SET @NR_DOCUMENTO = REPLACE(@NR_DOCUMENTO,'-','')

    DECLARE @NR_FORMATADO VARCHAR(MAX)
    
    
    IF (LEN(@NR_DOCUMENTO) = 14) BEGIN
        SET @NR_FORMATADO = 
            SUBSTRING(@NR_DOCUMENTO,1,2) + '.' + 
            SUBSTRING(@NR_DOCUMENTO,3,3) + '.' + 
            SUBSTRING(@NR_DOCUMENTO,6,3) + '/' + 
            SUBSTRING(@NR_DOCUMENTO,9,4) + '-' + 
            SUBSTRING(@NR_DOCUMENTO,13,2)
    END
    
    
    IF (LEN(@NR_DOCUMENTO) = 11) BEGIN	
        SET @NR_FORMATADO = 
            SUBSTRING(@NR_DOCUMENTO,1,3) + '.' + 
            SUBSTRING(@NR_DOCUMENTO,4,3) + '.' + 
            SUBSTRING(@NR_DOCUMENTO,7,3) + '-' + 
            SUBSTRING(@NR_DOCUMENTO,10,2)
    END
    
    IF (@NR_FORMATADO IS NULL) SET @NR_FORMATADO = @NR_DOCUMENTO
    
    RETURN @NR_FORMATADO
    
END