USE master
GO



DECLARE @TABLE TABLE
(
	CODIGO SMALLINT IDENTITY PRIMARY KEY CLUSTERED,
	VALOR INT,
	DATACRIACAO DATE,
	DATAMANIPULACAO DATE 
)

INSERT INTO @TABLE (VALOR, DATACRIACAO, DATAMANIPULACAO)  
OUTPUT INSERTED.CODIGO, INSERTED.VALOR, INSERTED.DATACRIACAO, INSERTED.DATAMANIPULACAO
VALUES (10, GETDATE(), GETDATE()+1),  (20, GETDATE(), GETDATE()+2),
       (30, GETDATE(), GETDATE()+3),  (40, GETDATE(), GETDATE()+4)


UPDATE @TABLE
SET DATAMANIPULACAO = DATEADD( MM ,1, DATAMANIPULACAO)
OUTPUT INSERTED.DATAMANIPULACAO AS 'DATA DE MANIPULAÇÃO ATUALIZADA',
       DELETED.DATAMANIPULACAO AS 'DATA DE MANIPULAÇÃO ANTIGA'
WHERE CODIGO=1


DELETE FROM @TABLE
OUTPUT DELETED.*
WHERE CODIGO IN (2,4)

/********************************************************************************************/

IF OBJECT_ID('TABLE2','U') IS NOT NULL
	DROP TABLE DBO.TABLE2;
CREATE TABLE TABLE2 
(
	CODIGO SMALLINT ,
	VALOR INT,
	DATACRIACAO DATE,
	DATAMANIPULACAO DATE
)

DECLARE @TABLE2 TABLE
(
	CODIGO SMALLINT,
	VALOR INT,
	DATACRIACAO DATE,
	DATAMANIPULACAO DATE
)

INSERT INTO TABLE2(VALOR, DATACRIACAO, DATAMANIPULACAO)
OUTPUT INSERTED.CODIGO, INSERTED.VALOR, INSERTED.DATACRIACAO, INSERTED.DATAMANIPULACAO INTO @TABLE2 
 VALUES(50, GETDATE(), GETDATE()+1),
       (60, GETDATE(), GETDATE()+2),
       (70, GETDATE(), GETDATE()+3),
       (80, GETDATE(), GETDATE()+4)


 SELECT * FROM @TABLE2