USE Treinamento
GO

-- WINDOW FRAME DEFAUT: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING

DECLARE	@TAB TABLE ([ID] INT IDENTITY(1,1),[ANO] INT ,[VLR] decimal(15,4))

Insert Into @TAB ([ANO],[VLR])
Values  (1999,120),(1999,121),(2001,122),(2001,123),(2001,124)
       ,(2000,125),(2000,126),(2000,127),(2000,128),(2002,129)

SELECT * FROM @TAB t	

--SELECT ID,ANO,VLR
--	,SUM(VLR) OVER(ORDER BY ANO RANGE UNBOUNDED PRECEDING) AS 'RANGE'
--	,SUM(VLR) OVER(ORDER BY ANO ROWS UNBOUNDED PRECEDING)  AS 'ROWS'
--FROM @TAB t	



;WITH T
AS
(

SELECT 
	 ID
	,ANO
	,VLR
	,SUM(VLR) OVER(PARTITION BY ANO ORDER BY ANO) AS 'VLR_ANO'
	,SUM(VLR) OVER(ORDER BY ANO) AS 'VLR_TOTAL'
	,SUM(VLR) OVER(ORDER BY ANO RANGE UNBOUNDED PRECEDING) AS 'RANGE'
	,SUM(VLR) OVER(ORDER BY ANO ROWS UNBOUNDED PRECEDING)  AS 'ROWS'
FROM @TAB t	
)
SELECT 
	 *
	,ROUND(VLR / VLR_ANO,4) * 100 '% RANGE'
	,ROUND([ROWS] / (SELECT SUM(VLR) FROM T), 4 ) * 100 '%ROWS'
FROM T 
