DECLARE @TABLEROLLUP TABLE  (
ALUNO VARCHAR(MAX),MATERIA VARCHAR(MAX),DIA_SEMANA VARCHAR(MAX))

INSERT INTO @TABLEROLLUP (ALUNO,MATERIA,DIA_SEMANA) 
VALUES ('ALUNOA','MATEMATICA','SEGUNDA'), ('ALUNOA','MATEMATICA','QUARTA')
, ('ALUNOA','MATEMATICA','QUINTA'), ('ALUNOA','FISICA','QUINTA')
, ('ALUNOA','PORTUGUES','SEXTA'), ('ALUNOA','FISICA','SEXTA')
, ('ALUNOB','MATEMATICA','QUARTA'), ('ALUNOB','MATEMATICA','QUINTA')
, ('ALUNOB','FISICA','QUINTA'), ('ALUNOB','PORTUGUES','QUARTA')
, ('ALUNOB','FISICA','SEXTA')


SELECT DIA_SEMANA, MATERIA, COUNT(ALUNO) AS QTD
FROM @TABLEROLLUP
GROUP BY MATERIA, DIA_SEMANA

SELECT DIA_SEMANA, MATERIA, COUNT(ALUNO) AS QTD
FROM @TABLEROLLUP
GROUP BY ROLLUP(DIA_SEMANA, MATERIA)
ORDER BY CASE WHEN DIA_SEMANA IS NULL THEN 1 ELSE 0 END, DIA_SEMANA, 
	     CASE WHEN MATERIA    IS NULL THEN 1 ELSE 0 END, MATERIA

