DECLARE @TEMPTABLE TABLE 
( [CLASS] CHAR(1) ,[ROLLNO] INT, [SECTION] CHAR(1), [MARKS] INT , [STUNAME] VARCHAR(50))

INSERT INTO @TEMPTABLE
VALUES
('A', 1, 'A', 80, 'MANOJ' ), ('A', 2, 'A', 70 ,'HARISH'), ('A', 3, 'A', 80 ,'KANCHAN'), ('A', 4, 'B', 90 ,'POOJA'),
('A', 5, 'B', 90 ,'SAURABH'), ('A', 6, 'B', 50 ,'ANITA'), ('B', 1, 'A', 60 ,'NITIN'), ('B', 2, 'A', 50 ,'KAMAR'),
('B', 3, 'A', 80 ,'DINESH'), ('B', 4, 'B', 90 ,'PARAS'), ('B', 5, 'B', 50 ,'LALIT'), ('B', 6, 'B', 70 ,'HEMA')
 
SELECT CLASS, ROLLNO, SECTION, MARKS, STUNAME 
FROM @TEMPTABLE


SELECT CLASS, SECTION, SUM(MARKS) [SUM]
FROM @TEMPTABLE
GROUP BY CLASS, SECTION WITH ROLLUP

SELECT CLASS, SECTION, SUM(MARKS) [SUM]
FROM @TEMPTABLE
GROUP BY CLASS, SECTION WITH CUBE

