DECLARE @TABLEROLLUP TABLE  (
ALUNO VARCHAR(MAX),MATERIA VARCHAR(MAX),DIA_SEMANA VARCHAR(MAX))

INSERT INTO @TABLEROLLUP (ALUNO,MATERIA,DIA_SEMANA) 
VALUES ('ALUNOA','MATEMATICA','SEGUNDA'), ('ALUNOA','MATEMATICA','QUARTA')
, ('ALUNOA','MATEMATICA','QUINTA'), ('ALUNOA','FISICA','QUINTA')
, ('ALUNOA','PORTUGUES','SEXTA'), ('ALUNOA','FISICA','SEXTA')
, ('ALUNOB','MATEMATICA','QUARTA'), ('ALUNOB','MATEMATICA','QUINTA')
, ('ALUNOB','FISICA','QUINTA'), ('ALUNOB','PORTUGUES','QUARTA')
, ('ALUNOB','FISICA','SEXTA')

--SELECT *
--FROM @TABLEROLLUP

--SELECT DIA_SEMANA, MATERIA, COUNT(ALUNO) AS QTD
--FROM @TABLEROLLUP
--GROUP BY MATERIA, DIA_SEMANA

SELECT 
	 COALESCE(DIA_SEMANA, 'TOTAL GERAL') AS 'DIA'
	,COALESCE( MATERIA, CASE WHEN DIA_SEMANA IS NULL AND MATERIA IS NULL THEN '' ELSE CONCAT(' >= TOTAL ', DIA_SEMANA) END) AS 'MATERIA'
	,COUNT(ALUNO) AS QTD
FROM @TABLEROLLUP
GROUP BY ROLLUP(DIA_SEMANA, MATERIA)
ORDER BY CASE WHEN DIA_SEMANA IS NULL THEN 1 ELSE 0 END, DIA_SEMANA, 
	     CASE WHEN MATERIA    IS NULL THEN 1 ELSE 0 END, MATERIA

SELECT DIA_SEMANA, MATERIA, COUNT(ALUNO) AS QTD
FROM @TABLEROLLUP
GROUP BY CUBE(DIA_SEMANA, MATERIA)
ORDER BY CASE WHEN DIA_SEMANA IS NULL THEN 1 ELSE 0 END, DIA_SEMANA, 
	     CASE WHEN MATERIA    IS NULL THEN 1 ELSE 0 END, MATERIA