USE CORPORERM
GO 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;

DECLARE @CODCOLIGADA INT			= 1				--:$CODCOLIGADA
DECLARE @DATAINICIAL DATETIME		= '2024-08-01'	--:DATAINCIAL_D
DECLARE @DATAFINAL DATETIME			= '2024-08-31'	--:DATAFINAL_D
--DECLARE @CODSECAO VARCHAR(35)		= '1.136.1478%'
DECLARE @CODSECAO VARCHAR(35)		= '1.001.0700.2310'
DECLARE @DATAFINALAJS DATETIME		= DATEADD(DAY,1,@DATAFINAL)

SELECT TOP 1 WITH TIES 
		 PH.CODCOLIGADA 
		,PH.CHAPA
		,PH.DTMUDANCA
		,PH.CODSECAO 	
	FROM DBO.PFHSTSEC PH
	WHERE PH.CODCOLIGADA = @CODCOLIGADA 
	AND ( PH.DTMUDANCA < @DATAFINALAJS ) 
	AND PH.CODSECAO LIKE CONCAT(@CODSECAO, '%')
	ORDER BY ROW_NUMBER() OVER(PARTITION BY PH.CODCOLIGADA, PH.CHAPA ORDER BY PH.CODCOLIGADA, PH.CHAPA , PH.DTMUDANCA DESC)

;WITH TAB
AS
(
	SELECT TOP 1 WITH TIES 
		 PH.CODCOLIGADA 
		,PH.CHAPA
		,PH.DTMUDANCA
		,PH.CODSECAO 	
	FROM DBO.PFHSTSEC PH
	WHERE PH.CODCOLIGADA = @CODCOLIGADA 
	AND ( PH.DTMUDANCA < @DATAFINALAJS ) 
	ORDER BY ROW_NUMBER() OVER(PARTITION BY PH.CODCOLIGADA, PH.CHAPA ORDER BY PH.CODCOLIGADA, PH.CHAPA , PH.DTMUDANCA DESC)
)
SELECT T.*, P.NOME 
FROM TAB T 
JOIN DBO.PFUNC P ON (T.CODCOLIGADA = P.CODCOLIGADA AND T.CHAPA = P.CHAPA)
WHERE ( P.CODSITUACAO NOT IN ('D') OR DATADEMISSAO >= @DATAINICIAL )
AND T.CODSECAO LIKE CONCAT(@CODSECAO, '%')
AND P.DATAADMISSAO < @DATAFINALAJS