DECLARE @TAB TABLE (
					NOME VARCHAR(30)
				   ,PONTUACAO1 DECIMAL(15,2) 
				   ,PONTUACAO2 DECIMAL(15,2)
				   ,PONTUACAO3 DECIMAL(15,2))

INSERT INTO @TAB VALUES ('Luis', 3,6,9), ('Marcio',4,7,10)

SELECT * FROM @TAB t

-- 1º Forma

SELECT NOME, MAX(TAB.PONTUACAO1) AS 'MAIOR'
FROM (
SELECT t.NOME, t.PONTUACAO1
FROM @TAB t

UNION ALL

SELECT t.NOME, t.PONTUACAO2
FROM @TAB t

UNION ALL

SELECT t.NOME, t.PONTUACAO3
FROM @TAB t 
	) AS TAB
GROUP BY NOME

-- 2º Forma

;WITH TAB (NOME, NOTAS)
AS 
(
	SELECT t.NOME, t.PONTUACAO1
	FROM @TAB t
	
	UNION ALL
	
	SELECT t.NOME, t.PONTUACAO2
	FROM @TAB t
	
	UNION ALL
	
	SELECT t.NOME, t.PONTUACAO3
	FROM @TAB t 

)
SELECT NOME, MAX(NOTAS) FROM TAB GROUP BY TAB.NOME


-- 3º Forma

SELECT t.NOME, MAX(n.NOTA)
FROM @TAB t
CROSS APPLY (VALUES(T.PONTUACAO1), (T.PONTUACAO2),(T.PONTUACAO3) ) AS n (NOTA)
GROUP BY NOME

SELECT *
FROM @TAB t
CROSS APPLY (VALUES(T.PONTUACAO1), (T.PONTUACAO2),(T.PONTUACAO3) ) AS n (NOTA)