/*
	EXEC XPCMDSHELL_SP_COPIA_ARQUIVO 
		 @DS_ARQUIVO = 'C:\Teste\t.txt'
		,@DS_DIRETORIO = 'C:\Teste\LUIS\'
		,@SOBRESCREVER = 0
		
	EXEC XPCMDSHELL_SP_COPIA_ARQUIVO 
		 @DS_ARQUIVO = 'C:\Teste\t.txt'
		,@DS_DIRETORIO = 'C:\Teste\LUIS\'
		,@SOBRESCREVER = 1
*/

CREATE OR ALTER PROC XPCMDSHELL_SP_COPIA_ARQUIVO
(
	 @DS_ARQUIVO VARCHAR(6000)
	,@DS_DIRETORIO VARCHAR(8000)
	,@SOBRESCREVER BIT = 0
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE 
		@QUERY VARCHAR(8000),
		@NOME_ARQUIVO_DESTINO VARCHAR(500) = @DS_DIRETORIO + REVERSE(LEFT(REVERSE(@DS_ARQUIVO), CHARINDEX('\',REVERSE(@DS_ARQUIVO),1) -1 )),
		@RESULTADO VARCHAR(MAX)

	IF @SOBRESCREVER = 0 
		SET @QUERY = ' IF EXIST "' + @NOME_ARQUIVO_DESTINO + '" ( ECHO Arquivo já existe ) ELSE ( COPY "' + @DS_ARQUIVO + '" "' + @DS_DIRETORIO + '")'
	ELSE 
		SET @QUERY = ' COPY ' + (CASE WHEN @SOBRESCREVER = 1 THEN '/Y' ELSE '' END ) + ' "' + @DS_ARQUIVO + '" "' + @DS_DIRETORIO + '"'

	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))

	INSERT INTO @RETORNO
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY
	
	--SELECT @QUERY
	--SELECT * FROM @RETORNO
	SELECT RESULTADO  FROM @RETORNO WHERE LINHA = 1

END
GO

