/*
	EXEC XPCMDSHELL_SP_APAGA_ARQUIVO 'C:\Teste\t\tT.txt'
*/

CREATE OR ALTER PROC XPCMDSHELL_SP_APAGA_ARQUIVO
(
	@DS_ARQUIVO VARCHAR(6000)
)
AS
BEGIN
	
	SET NOCOUNT ON 

	DECLARE @QUERY VARCHAR(6000) = 'del /F /Q "' + @DS_ARQUIVO
	
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	INSERT INTO @RETORNO 
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY

	SELECT CASE WHEN LEN(RESULTADO)>1 THEN 0 ELSE 1 END  FROM @RETORNO WHERE LINHA = 1

END
GO