/*
	EXEC XPCMDSHELL_SP_ESCREVE_ARQUIVO 
		 @DS_ARQUIVO = 'C:\Teste\t\tT.txt'
		,@DS_TEXTO = 'kMEU TESTE'
		,@SOBRESCREVER = 1
*/

CREATE OR ALTER PROC XPCMDSHELL_SP_ESCREVE_ARQUIVO
(
	 @DS_ARQUIVO VARCHAR(6000)
	,@DS_TEXTO VARCHAR(8000)
	,@SOBRESCREVER BIT = 0
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @QUERY VARCHAR(8000) = 'ECHO "' + @DS_TEXTO + '"' +
		(CASE WHEN @SOBRESCREVER = 1 THEN ' > ' ELSE ' >> ' END) +
		'"' + @DS_ARQUIVO + '"'
	
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	
	INSERT INTO @RETORNO
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY
	SELECT CASE WHEN LEN(RESULTADO)>1 THEN 0 ELSE 1 END  FROM @RETORNO WHERE LINHA = 1

END
GO