/*
	XPCMDSHELL_SP_LISTAR_ARQUIVOS 
		 @DS_ARQUIVO = 'C:\Users\'

*/

CREATE OR ALTER PROC XPCMDSHELL_SP_LISTAR_ARQUIVOS
(
	 @DS_ARQUIVO VARCHAR(6000)
)
AS
BEGIN

	DECLARE @QUERY VARCHAR(6000) = 'dir/ -C /4 /N "' + @DS_ARQUIVO + '"'
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	DECLARE @TABELA_FINAL TABLE (LINHA INT IDENTITY (1,1), DT_CRIACAO DATETIME, TIPO BIT, TAMANHO VARCHAR(MAX), ARQUIVO VARCHAR(255))

	INSERT INTO @RETORNO
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY
	
	INSERT INTO @TABELA_FINAL (DT_CRIACAO,TIPO,TAMANHO,ARQUIVO)
	SELECT 
		 CONVERT(DATETIME, LEFT(RESULTADO,20)) AS DT_CRIACAO
		,0 AS TIPO
		,0 AS TAMANHO
		,TRIM(SUBSTRING(RESULTADO,37,LEN(RESULTADO))) AS ARQUIVO
	FROM @RETORNO
	WHERE RESULTADO IS NOT NULL
	AND LINHA >= 6
	AND LINHA < (SELECT MAX(LINHA) FROM @RETORNO) -2
	AND RESULTADO LIKE '%<DIR>%'
	AND TRIM(SUBSTRING(RESULTADO,37,LEN(RESULTADO))) NOT IN ('.','..')
	ORDER BY ARQUIVO

	INSERT INTO @TABELA_FINAL (DT_CRIACAO,TIPO,TAMANHO,ARQUIVO)
	SELECT 
		 CONVERT(DATETIME, LEFT(RESULTADO,20)) AS DT_CRIACAO
		,1 AS TIPO
		,CAST(LTRIM(SUBSTRING(LTRIM(RESULTADO),21,19)) AS VARCHAR(MAX)) AS TAMANHO
		,TRIM(SUBSTRING(RESULTADO, CHARINDEX(LTRIM(SUBSTRING(LTRIM(RESULTADO),21,19)), RESULTADO, 21) + LEN(LTRIM(SUBSTRING(LTRIM(RESULTADO),21,19))) ,100)) AS ARQUIVO
	FROM @RETORNO
	WHERE RESULTADO IS NOT NULL
	AND LINHA >= 6
	AND LINHA < (SELECT MAX(LINHA) FROM @RETORNO) -2
	AND RESULTADO LIKE '%<DIR>%'
	AND TRIM(SUBSTRING(RESULTADO,37,LEN(RESULTADO))) NOT IN ('.','..')
	ORDER BY ARQUIVO

	SELECT * FROM @TABELA_FINAL 

END
GO
