/*    
	EXEC XPCMDSHELL_SP_CRIA_DIRETORIO 'C:\Teste\t'
*/

CREATE OR ALTER PROC XPCMDSHELL_SP_CRIA_DIRETORIO
(
	@DS_DIRETORIO VARCHAR(6000)
)
AS 
BEGIN 
	DECLARE @QUERY VARCHAR(6000) = 'mkdir "' + @DS_DIRETORIO + '"'

	
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	
	INSERT INTO @RETORNO
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY
	
	SELECT CASE WHEN LEN(RESULTADO)>1 THEN 0 ELSE 1 END AS RESULTADO FROM @RETORNO WHERE LINHA = 1
END
GO
