/*
	EXEC XPCMDSHELL_SP_APAGA_DIRETORIO 'C:\Teste\'
*/

CREATE OR ALTER PROC XPCMDSHELL_SP_APAGA_DIRETORIO
(
	@DS_ARQUIVO VARCHAR(6000),
	@RECURSIVO BIT = 0 
)
AS
BEGIN

	SET NOCOUNT ON 

	DECLARE @QUERY VARCHAR(6000) = 'RMDIR ' + (CASE WHEN @RECURSIVO = 1 THEN ' /S' ELSE '' END) + ' /Q "' + @DS_ARQUIVO + '"'
	
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	INSERT INTO @RETORNO 
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY

	SELECT CASE WHEN LEN(RESULTADO)>1 THEN 0 ELSE 1 END  FROM @RETORNO WHERE LINHA = 1

END
GO