/*
	DECLARE @SAIDA BIT;


	EXEC XPCMDSHELL_SP_ARQUIVO_EXISTE
		 @DS_ARQUIVO = 'C:\temp'
		,@SAIDA = @SAIDA OUTPUT
	
	SELECT @SAIDA


*/


CREATE OR ALTER PROC XPCMDSHELL_SP_ARQUIVO_EXISTE 
(
	@DS_ARQUIVO VARCHAR(500),
	@SAIDA BIT OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON 

	DECLARE @QUERY VARCHAR(6000) = 'IF EXIST "' + @DS_ARQUIVO + '" ( echo 1 ) ELSE ( echo 0 ) '
	
	DECLARE @RETORNO TABLE (LINHA INT IDENTITY (1,1), RESULTADO VARCHAR(MAX))
	INSERT INTO @RETORNO 
	EXEC MASTER.SYS.XP_CMDSHELL @COMMAND_STRING = @QUERY

	IF EXISTS (SELECT 1 FROM @RETORNO)
		SELECT @SAIDA = RESULTADO FROM @RETORNO WHERE LINHA = 1
	ELSE 
		SET @SAIDA = 0
END
GO