SELECT TABELAS.NAME AS TABELA,
	   COLUNAS.NAME AS COLUNA,
	   TIPOS.NAME AS TIPO,
	   COLUNAS.LENGTH AS TAMANHO,
	   COLUNAS.ISNULLABLE AS NULO
	   --,'SELECT ' + CHAR(39) + TABELAS.name + CHAR(39) + ' TABELA, COUNT(*) FROM ' + TABELAS.name + ' WHERE CODTRB=' + CHAR(39) +'ICMSH' + CHAR(39)
FROM SYSOBJECTS TABELAS
INNER JOIN SYSCOLUMNS COLUNAS ON (TABELAS.ID = COLUNAS.ID)
INNER JOIN SYSTYPES TIPOS ON (COLUNAS.USERTYPE = TIPOS.USERTYPE)
WHERE TABELAS.XTYPE = 'U' /*’U’ = TABELAS*/
  AND COLUNAS.name like '%a%'
  --AND TABELAS.name LIKE 'P%'
ORDER BY TABELAS.NAME

