DECLARE @TABLE VARCHAR(MAX) = 'C8X010' + '%'
DECLARE @TABLEREF VARCHAR(MAX) = 'TPRODUTODEF'

SELECT UPPER(TC.TABLE_NAME) AS PRIMARYKEYTABLE,
	UPPER(TC.CONSTRAINT_NAME) AS PRIMARYKEY,
	UPPER(COALESCE(TC2.TABLE_NAME, 'N/A')) AS FOREIGNKEYTABLE,
	UPPER(COALESCE(RC1.CONSTRAINT_NAME, 'N/A')) AS FOREIGNKEY,
	*
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC1 ON TC.CONSTRAINT_NAME = RC1.UNIQUE_CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC2 ON TC2.CONSTRAINT_NAME = RC1.CONSTRAINT_NAME
WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
	--AND TC.TABLE_NAME LIKE @TABLE
	--AND TC2.TABLE_NAME LIKE @TABLEREF
ORDER BY TC.TABLE_NAME,
	TC.CONSTRAINT_NAME,
	RC1.CONSTRAINT_NAME
